### ISSUE TITLE
Invalid opcodes: ror / rol

### ISSUE THREAD

**Issue by axic** [huff-language/huffc#10]
See https://github.com/huff-language/huffc/blob/master/src/evm/opcodes.ts#L145-L146

These were initially planned for https://eips.ethereum.org/EIPS/eip-145, but did not make it into the protocol update.

(Additionally the opcode list is out of order.)

**Comment by d1ll0n** [comment]
Thanks for making this issue!
We're also missing selfbalance and basefee
