### ISSUE TITLE
How to pass arguments to the constructor?

### ISSUE THREAD

**Issue by Kayaba-Attribution** [huff-language/huffc#26]
⊂(◉‿◉)つ HI!

I saw Huff and wanted to give it a try, is there any documentation available that explains the `takes(0) returns (0)` syntax on the macros?

+ How to pass an address to the constructor?

Tried to do it this way:

```
/* Constructor */
#define constant TEST_LOCATION = FREE_STORAGE_POINTER()

#define macro CONSTRUCTOR() = takes(1) returns (0) {
    [TEST_LOCATION] sstore
    // Set msg.sender as the owner of the contract.
    OWNABLE_CONSTRUCTOR()
}
```

and

```js
    const Token = await ethers.getContractFactory("ERC20");
    token = await Token.deploy("0x0000000000000000000000000000000000000000");
    await token.deployed();
```

But it says wrong number of arguments, expecting 0 got 1

**Comment by virtualjpeg** [comment]
the `takes` and `returns` syntax effectively denotes the values the macro *takes* of the stack and the values it adds, or *returns* onto the stack.

as an example, a macro that performs basic addition would have the annotation `takes (2) returns (1)`, as it takes two existing values from the stack (as an example: 3 and 2) and finally puts the result (5) on the stack.

if you want to pass an argument, you can do it as you do with a normal programming language.

**Comment by virtualjpeg** [comment]
also note that the compiler does not enforce these annotations - they are purely for readability.

**Comment by jtriley2p** [comment]
Here is an ERC721 constructor example with the name and symbol:
https://github.com/exp-table/huffc/blob/0d572fc6131804fd1785df97d70d9451d05c4460/examples/erc721/contracts/ERC721.huff#L44

Constructor arguments are each padded to 32 bytes and appended to the end of the deployment bytecode.

You should be able to access an address by extracting the first 32 byte constructor argument as follows.

```
#define constant TEST_LOCATION = FREE_STORAGE_POINTER()

#define macro CONSTRUCTOR = takes (0) returns (0) {
    0x20                   // [arg0_size]
    0x20 codesize sub      // [arg0_offset, arg0_size]
    0x00                   // [mem_offset, arg0_offset, arg0_size]
    codecopy               // []
    0x00                   // [mem_offset]
    mload                  // [arg0]
    [TEST_LOCATION] sstore // []
}
```

**Comment by Kayaba-Attribution** [comment]
@virtualjpeg , @JoshuaTrujillo15 Thank you for your help!

The example was awesome, I might go ahead and add the name and symbol for the ERC20 example (ᵔᴥᵔ)
