### ISSUE TITLE
bug(compiler): unable to parse arrays as inputs or outputs

### ISSUE THREAD

**Issue by exp-table** [huff-language/huffc#28]
The compiler cannot parse functions of the interface if they either use arrays for inputs or outputs.

The error probably lies in the regex definitions [here](https://github.com/huff-language/huffc/blob/b788d6f0b9a8c48551a8c089b754f47acd5f7a3c/src/parser/syntax/defintions.ts#L71).
They do not account for `[]`.

To recreate the issue, try to compile any file with the following functions

```js
#define function set(uint256,uint256[]) nonpayable returns ()
#define function get(uint256) view returns (uint256[])
```

**Comment by sudovirtual** [comment]
fix here: https://github.com/huff-language/huffc/pull/32
